#!/usr/bin/env python3

import argparse
import sys
from cookie_finder import parse_cookie_log, find_most_active_cookies
from datetime import datetime 


def main():
    parser = argparse.ArgumentParser(description="Find the most active cookie(s) for a given date")
    parser.add_argument("filename", help="path to cookie log CSV file")
    parser.add_argument("-d", required=True, help="date in YYYY-MM-DD format")
    args = parser.parse_args()
    

    #correct date format 
    try:
        parsed = datetime.strptime(args.d, "%Y-%m-%d")
        if parsed.strftime("%Y-%m-%d") != args.d:
            raise ValueError
    except ValueError:
        print(f"Error: Date '{args.d}' must be in YYYY-MM-DD format", file=sys.stderr)
        sys.exit(1)

    #parse cookie log 
    try:
        entries = parse_cookie_log(args.filename)
    except FileNotFoundError:
        print(f"Error: File '{args.filename}' is not found", file=sys.stderr)
        sys.exit(1)
    
    #find most active cookies and print 
    for cookie in find_most_active_cookies(args.d, entries):
        print(cookie)


if __name__ == "__main__":
    main()
